### ISSUE TITLE
 پرداخت های این ترمینال فقط از طریق توکن امکانپذیر است.

### ISSUE THREAD

**Issue by mohammaddan** [php-monsters/laravel-online-payment#38]
سلام خسته نباشید و تشکر از پکیج خیلی مفیدتون
من یک مشکلی دارم با درگاه بانک سامان، ظاهرا الان فقط با حالت توکن کار میکنه و داخل کدهاتون را نگاه کردم و دیدم که داخل فرم بانک سامان جا برای توکن گذاشته بودین ولی جایی رو که بشه انتخاب کرد که از روش توکن تراکنش انجام بشه رو پیدا نکردم

**Comment by amidesfahani** [comment]
لطفا به این مورد رسیدگی کنید. هیچ گزینه ای جز تغییر دستی برای استفاده از قابلیت توکن وجود نداره و مقدار with_token برای درایور سامان رو نمیشه تغییر داد
و مورد دیگه گویا موارد به درستی کنترل نشده!

```
 Tartan\Larapay\Adapter\Saman::generateFormWithToken(): Return value must be of type string, Illuminate\View\View returned 
```

**Comment by samuraee** [comment]
مشکل در ورژن v8.1.3 حل شد
