### ISSUE TITLE
Class "Tartan\Log\XLogServiceProvider" not found

### ISSUE THREAD

**Issue by mohammaddan** [php-monsters/laravel-online-payment#48]
Hi my friends.
I add **Tartan\Log\XLogServiceProvider::class** in **config/app.php** and get error:

**Class "Tartan\Log\XLogServiceProvider" not found**,

Then i look at  your codes and see:
**XLogServiceProvider**  and **XLog** are in **\PhpMonsters\Log** namespace but you use it as  **Tartan\Log\Facades** namespace.

**Comment by samuraee** [comment]
package namespace completely changed from Tartan to PhpMonsters. Why have you used the old namespace?
As I can there are no remaining Tartan in the latest version of codes!!!
